import data
import model
import pickle
import random
from nltk import pos_tag

def fourgramspoem(poems, words):
    print("\t\tThe Poem generated by a 4-gram model!")
    pickle_in = open("FourGram.pickle","rb")
    FourGram = pickle.load(pickle_in)
    pickle_in.close()

    word1, word2, word3 = words

    print("*"*80)
    generate_str = word1+" "+word2 + " " +word3
    for i in range(60):
        next_word  = FourGram.next_word([word1, word2, word3])
        word1      = word2
        word2      = word3
        word3      = next_word
        generate_str = generate_str+" "+ next_word
    print(generate_str.replace("NEWLINE ","\n"))
    print("*"*80)

def input_words():
    word1  = (input("Please enter the first word\n"))

    pickle_in = open("FourGram.pickle","rb")
    FourGram = pickle.load(pickle_in)
    pickle_in.close()

    temp   = list(FourGram.model[word1].items())
    word2  = temp[random.randint(0,len(temp)-1)][0]
    temp2  = list(FourGram.model[word1][word2].items())
    word3  = temp2[random.randint(0,len(temp2)-1)][0]

    return(word1,word2,word3)

def poems_by_syllables(poems, words):
    print("\t\tThe Poem generated by a 4-gram model Combined with Syllable Model!")

    FourGram         = model.nGrams(poems.poems, 4, alpha = 0.15)
    FourGramSyllable = model.nGrams(poems.poems_of_syllables , 4, alpha = 0.35)

    word1, word2, word3 = words

    print("*"*80)
    generate_str = word1+" "+word2 + " " +word3
    for i in range(120):
        next_word  = model.nextSyllableWord([word1,word2,word3], FourGram, FourGramSyllable, poems.word_syllablecount_dict, 4)
        word1      = word2
        word2      = word3
        word3      = next_word
        generate_str = generate_str+" "+ next_word
    print(generate_str.replace("NEWLINE ","\n"))
    print("*"*80)

def poems_by_POS(poems, words):
    print("\t\tThe Poem generated by a 4-gram model combined with Part Of Speech tags!")

    FourGram         = model.nGrams(poems.poems, 4, alpha = 0.5)
    FourGramPOS      = model.nGrams(poems.poems_of_POStags, 4, 0.50)

    word1,word2,word3 = words
    temp = [tag for word, tag in pos_tag([word1, word2, word3])]
    POSt1, POSt2, POSt3 = temp[0], temp[1], temp[2]

    print("*"*80)
    generate_str = word1+" "+word2 + " " +word3
    for i in range(100):
        next_word,next_tag = model.nextPOSWord([word1,word2,word3],
                                                [POSt1,POSt2,POSt3],
                                                FourGram, FourGramPOS, poems.word_POStag_dict, 0.5)
        word1 = word2
        word2 = word3
        word3 = next_word
        POSt1 = POSt2
        POSt2 = POSt3
        POSt3 = next_tag
        generate_str = generate_str+" "+ next_word
    print(generate_str.replace("NEWLINE ","\n"))
    print("*"*80)

def poems_by_POS_Syllable(poems, words):
    print("\t\tThe Poem generated by a 4-gram model combined with Syllables and POS tags!")

    FourGram         = model.nGrams(poems.poems, 4, alpha = 0.2)
    FourGramPOS      = model.nGrams(poems.poems_of_POStags, 4, alpha = 0.25)
    FourGramSyllable = model.nGrams(poems.poems_of_syllables , 4, alpha = 0.5)

    word1,word2,word3 = words
    temp = [tag for word, tag in pos_tag([word1, word2, word3])]
    POSt1, POSt2, POSt3 = temp[0], temp[1], temp[2]

    generate_str = word1+" "+word2 + " " +word3
    for i in range(100):
        next_word,next_tag = model.nextPOSWordSyllable([word1,word2,word3],
                                                       [POSt1,POSt2,POSt3],
                                                       FourGram, FourGramPOS, FourGramSyllable,
                                                       poems.word_POStag_dict, poems.word_syllablecount_dict,
                                                       0.5)
        word1 = word2
        word2 = word3
        word3 = next_word
        POSt1 = POSt2
        POSt2 = POSt3
        POSt3 = next_tag
        generate_str = generate_str+" "+ next_word
    print(generate_str.replace("NEWLINE ","\n"))


def main():
    pickle_in = open("poems.pickle","rb")
    poems = pickle.load(pickle_in)
    pickle_in.close()

    words = input_words()

    fourgramspoem(poems, words)
    poems_by_syllables(poems, words)
    poems_by_POS(poems, words)
    poems_by_POS_Syllable(poems, words)

if __name__ == '__main__':
    main()
